"use client";

import { useState } from "react";
import { Panel, PanelHeader, PageTitle, StatusPill, SourceChip } from "@/components/ui";
import { ReportView } from "@/components/viz/ReportView";
import { deliverables } from "@/lib/data";
import { useLive, fetchDeliverables, type LiveDeliverable } from "@/lib/live";
import { buildReportText, downloadText } from "@/lib/report";
import {
  FileText,
  FileType2,
  FileSpreadsheet,
  Code2,
  Presentation,
  ClipboardCheck,
  Eye,
  Download,
  Send,
  X,
} from "lucide-react";

const categoryIcon: Record<string, React.ReactNode> = {
  "Engineering Report": <FileText className="h-4 w-4" />,
  "Approval Note": <ClipboardCheck className="h-4 w-4" />,
  "Management Presentation": <Presentation className="h-4 w-4" />,
  "Excel Analysis": <FileSpreadsheet className="h-4 w-4" />,
  Code: <Code2 className="h-4 w-4" />,
  "Inspection Summary": <FileType2 className="h-4 w-4" />,
};

const categories = [
  "Engineering Report",
  "Approval Note",
  "Management Presentation",
  "Excel Analysis",
  "Code",
  "Inspection Summary",
];

export default function DeliverablesPage() {
  const { data: items, source } = useLive<LiveDeliverable[]>(fetchDeliverables, deliverables as LiveDeliverable[]);
  const [showReport, setShowReport] = useState(false);
  const [sent, setSent] = useState<string | null>(null);

  function handleView(d: LiveDeliverable) {
    if (d.downloadUrl) window.open(d.downloadUrl, "_blank");
    else if (d.id === "del-1") setShowReport(true);
    else downloadText(`KAVACH_${d.id}.txt`, buildReportText());
  }

  function handleDownload(d: LiveDeliverable) {
    if (d.downloadUrl) {
      // Real file generated by the FastAPI backend (PDF/DOCX/XLSX/TXT).
      window.open(d.downloadUrl, "_blank");
      return;
    }
    // Client-side offline export when running standalone.
    const ext = d.format.toLowerCase() === "code" ? "txt" : d.format.toLowerCase();
    downloadText(`KAVACH_deliverable_${d.id}.${ext}`, buildReportText());
  }

  return (
    <div>
      <PageTitle eyebrow="Professional Outputs" title="Deliverables">
        <div className="flex items-center gap-2">
          <SourceChip source={source} />
          <StatusPill tone="verified" dot={false}>
            {items.length} generated
          </StatusPill>
        </div>
      </PageTitle>

      {/* categories */}
      <div className="mb-3 grid grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-6">
        {categories.map((c) => {
          const n = items.filter((d) => d.category === c).length;
          return (
            <Panel key={c}>
              <div className="flex items-center gap-2.5 p-3">
                <span className="grid h-8 w-8 place-items-center rounded-[3px] border border-line bg-surface-inset text-signal">
                  {categoryIcon[c]}
                </span>
                <div>
                  <div className="text-2xs text-ink-muted">{c}</div>
                  <div className="font-display text-lg font-bold text-ink">{n}</div>
                </div>
              </div>
            </Panel>
          );
        })}
      </div>

      {/* list */}
      <div className="grid gap-3 md:grid-cols-2">
        {items.map((d) => (
          <Panel key={d.id}>
            <div className="p-4">
              <div className="mb-3 flex items-start justify-between gap-3">
                <div className="flex items-start gap-2.5">
                  <span className="grid h-9 w-9 place-items-center rounded-[3px] border border-line bg-surface-inset text-signal">
                    {categoryIcon[d.category]}
                  </span>
                  <div>
                    <h3 className="text-sm font-semibold text-ink">{d.title}</h3>
                    <div className="mt-0.5 font-mono text-2xs text-ink-faint">
                      {d.category} · {d.project} · {d.createdAt}
                    </div>
                  </div>
                </div>
                <span className="font-mono text-2xs text-ink-faint">{d.format} · {d.sizeKb} KB</span>
              </div>

              <div className="mb-3 flex flex-wrap gap-1">
                {d.sections.map((s) => (
                  <span key={s} className="rounded-[2px] border border-line bg-surface-inset px-1.5 py-0.5 font-mono text-2xs text-ink-muted">
                    {s}
                  </span>
                ))}
              </div>

              <div className="mb-3 flex items-center gap-3">
                <span className="font-mono text-2xs text-ink-faint">AI confidence</span>
                <span className="font-mono text-2xs text-ink">{d.confidence}%</span>
                {d.humanReview ? (
                  <StatusPill tone="caution" dot={false}>Human review required</StatusPill>
                ) : (
                  <StatusPill tone="verified" dot={false}>Cleared</StatusPill>
                )}
              </div>

              <div className="flex items-center gap-1.5">
                <button onClick={() => handleView(d)} className="btn btn-ghost flex-1">
                  <Eye className="h-3.5 w-3.5" /> View
                </button>
                <button onClick={() => handleDownload(d)} className="btn btn-ghost flex-1">
                  <Download className="h-3.5 w-3.5" /> Download
                </button>
                <button
                  onClick={() => setSent(d.id)}
                  className="btn btn-primary flex-1"
                >
                  <Send className="h-3.5 w-3.5" /> {sent === d.id ? "Sent" : "Review"}
                </button>
              </div>
            </div>
          </Panel>
        ))}
      </div>

      {showReport && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-canvas/80 p-4 backdrop-blur-sm" onClick={() => setShowReport(false)}>
          <div className="panel-raised h-[88vh] w-full max-w-4xl overflow-hidden" onClick={(e) => e.stopPropagation()}>
            <ReportView onClose={() => setShowReport(false)} />
          </div>
        </div>
      )}
    </div>
  );
}
